# Generated by Django 5.0.1 on 2024-02-03 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cars',
            name='slug',
            field=models.SlugField(blank=True, default=' ', max_length=255),
        ),
        migrations.AlterField(
            model_name='cars',
            name='time_create',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
