# Generated by Django 5.0.1 on 2024-02-07 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0006_uploadf'),
    ]

    operations = [
        migrations.AddField(
            model_name='cars',
            name='photo',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='photos/%Y/%m%d', verbose_name='Фото'),
        ),
    ]
